- name: Apt prerequisites
  ansible.builtin.apt:
    name:
      - software-properties-common
      - python3-apt
      - gpg
    state: present
    update_cache: true

- name: ppa deadsnakes/ppa
  command:
    cmd: add-apt-repository -y ppa:deadsnakes/ppa
    creates: "/etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-resolute.sources"

- name: Apt packages for python
  apt:
    name:
      - python3.13
      - python3-virtualenv

- name: Virtual env for chatbot
  command:
    cmd: virtualenv /srv/chatbot/venv -p python3.13 # TODO
    creates: "/srv/chatbot/venv"

- name: Git checkout
  git:
    repo: "https://github.com/epfl-si/polylex-chatbot.git"
    dest: /srv/chatbot/src
    version: "improve_retrieval_task" # TODO
    force: yes

- name: Python requirements
  ansible.builtin.pip:
    requirements: /srv/chatbot/src/requirements.txt
    virtualenv: /srv/chatbot/venv

- name: /etc/systemd/system/polylex-chatbot.service
  copy:
    content: |
      [Unit]
      Description=Polylex Chatbot
      After=multi-user.target
      
      [Service]
      Type=simple
      Restart=always
      Environment="PATH=/srv/chatbot/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      Environment="VIRTUAL_ENV=/srv/chatbot/venv"
      WorkingDirectory=/srv/chatbot/src
      ExecStart=/srv/chatbot/venv/bin/python3 /srv/chatbot/src/app/app.py
      
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/polylex-chatbot.service

- name: Polylex Chatbot service
  systemd_service:
    name: polylex-chatbot.service
    state: started
    enabled: true
