- include_tasks:
    file: vm.yml
    apply:
      tags: vm
  tags: vm

- include_tasks:
    file: db.yml
    apply:
      tags: db
  tags: db

- include_tasks:
    file: monitoring.yml
    apply:
      tags: monitoring
  tags: monitoring

- include_tasks:
    file: rag.yml
    apply:
      tags: rag
  tags: rag
