# TODO : verifier que dossiers / hierarchie ok + dossier data / stats au bon endroit selon config.py (trop haut mtn)
- name: RAG directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /srv/rag
    - /srv/rag/scr
    - /srv/rag/chatbot
  become: true

- name: Apt prerequisites
  apt:
    name:
      - software-properties-common
      - python3-apt
      - gpg
      - openjdk-21-jre-headless
      - tesseract-ocr
    state: present
    update_cache: true

- name: ppa deadsnakes/ppa
  command:
    cmd: add-apt-repository -y ppa:deadsnakes/ppa
    creates: "/etc/apt/sources.list.d/deadsnakes-ubuntu-ppa-resolute.sources"

- name: Apt cache cleaning
  apt:
    autoclean: true
    autoremove: true
  become: true

- name: Pip cache removed
  file:
    path: /root/.cache/pip
    state: absent
  become: true

- name: Apt packages for python
  apt:
    name:
      - python3.13
      - python3-virtualenv

- name: Virtual env for rag
  command:
    cmd: virtualenv /srv/rag/venv -p python3.13
    creates: "/srv/rag/venv"

- name: Python requirements file
  copy:
    src: ../../../requirements.txt
    dest: /srv/rag/requirements.txt
    owner: root
    group: root
    mode: "0644"

- name: Python requirements
  pip:
    requirements: /srv/rag/requirements.txt
    virtualenv: /srv/rag/venv
    extra_args: --no-cache-dir

- name: Playwright Chromium
  command: /srv/rag/venv/bin/python3 -m playwright install --with-deps chromium
  become: true
  environment:
    PLAYWRIGHT_BROWSERS_PATH: /srv/rag/ms-playwright
  changed_when: false

- name: Env file
  template:
    src: .env
    dest: /srv/rag/.env
    owner: root
    group: root
    mode: "0644"

- name: RAG source directory
  copy:
    src: ../../../src/
    dest: /srv/rag/src/
    owner: root
    group: root
    mode: "0644"

# TODO : verifier que run ok avec PYTHONPATH
# TODO : executer les scripts uniquement si besoin avec tag a part
- name: Script to build corpus
  command: /srv/rag/venv/bin/python3 scripts/build_corpus.py
  args:
    chdir: /srv/rag
  environment:
    PYTHONPATH: /srv/rag/src

# TODO : verifier que run ok avec PYTHONPATH
# TODO : executer les scripts uniquement si besoin avec tag a part
- name: Script to index corpus
  command: /srv/rag/venv/bin/python3 scripts/index_corpus.py
  args:
    chdir: /srv/rag
  environment:
    PYTHONPATH: /srv/rag/src

- name: Chatbot source directory
  synchronize:
    src: ../../../app/
    dest: /srv/rag/chatbot/
    delete: true
    rsync_opts:
      - "--exclude=.env"

- name: /etc/systemd/system/polylex-chatbot.service
  copy:
    content: |
      [Unit]
      Description=Polylex Chatbot
      After=multi-user.target
      
      [Service]
      Type=simple
      Restart=always
      Environment="PATH=/srv/rag/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      Environment="VIRTUAL_ENV=/srv/rag/venv"
      WorkingDirectory=/srv/rag/chatbot
      EnvironmentFile=/srv/rag/.env
      ExecStart=/srv/rag/venv/bin/chainlit run app.py --host 0.0.0.0 --port 80
      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/polylex-chatbot.service

- name: Polylex Chatbot service
  systemd_service:
    name: polylex-chatbot.service
    state: started
    enabled: true
