- include_tasks:
    file: vm.yml
    apply:
      tags: vm
  tags: always

- include_tasks:
    file: db.yml
    apply:
      tags: db
  tags: always

- include_tasks:
    file: monitoring.yml
    apply:
      tags: monitoring
  tags: always

- include_tasks:
    file: rag.yml
    apply:
      tags: rag
  tags: always
