- name: RAG directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  loop:
    - /srv/rag
    - /srv/rag/src
    - /srv/rag/scripts
    - /srv/rag/chatbot
  become: true

- name: Python venv and packages
  block:
    - name: Virtual env for rag
      command:
        cmd: virtualenv /srv/rag/venv -p python3.12
        creates: "/srv/rag/venv"

    - name: Python requirements file
      copy:
        src: ../../requirements.txt
        dest: /srv/rag/requirements.txt
        owner: root
        group: root
        mode: "0644"

    - name: Python requirements
      pip:
        requirements: /srv/rag/requirements.txt
        virtualenv: /srv/rag/venv
        extra_args: --no-cache-dir

    - name: Playwright Chromium
      command: /srv/rag/venv/bin/python3 -m playwright install --with-deps chromium
      become: true
      environment:
        PLAYWRIGHT_BROWSERS_PATH: /srv/rag/ms-playwright

- name: Code copy
  tags:
    - new_release
  notify:
    - Polylex Chatbot restart
  block:
    - name: Env file
      template:
        src: .env
        dest: /srv/rag/.env
        owner: root
        group: root
        mode: "0644"

    - name: RAG src directory
      copy:
        src: ../../src/
        dest: /srv/rag/src/
        owner: root
        group: root
        mode: "0644"

    - name: RAG scripts directory
      copy:
        src: ../../scripts/
        dest: /srv/rag/scripts/
        owner: root
        group: root
        mode: "0644"

- name: Corpus build and indexation
  tags:
    - new_corpus
    - new_release
  block:
    - name: Script to build corpus
      command: /srv/rag/venv/bin/python3 scripts/build_corpus.py
      args:
        chdir: /srv/rag
      environment:
        PYTHONPATH: /srv/rag/src

    - name: Script to index corpus
      command: /srv/rag/venv/bin/python3 scripts/index_corpus.py --env-path=".env"
      args:
        chdir: /srv/rag
      environment:
        PYTHONPATH: /srv/rag/src
      notify:
        - Polylex Chatbot restart

- name: Chatbot setup
  tags:
    - new_release
  block:
    - name: Chatbot source directory
      copy:
        src: ../../app/
        dest: /srv/rag/chatbot/
        owner: root
        group: root
        mode: "0644"
      notify:
        - Polylex Chatbot restart

    - name: /etc/systemd/system/polylex-chatbot.service
      copy:
        content: |
          [Unit]
          Description=Polylex Chatbot
          After=multi-user.target
          
          [Service]
          Type=simple
          Restart=always
          Environment="PATH=/srv/rag/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
          Environment="VIRTUAL_ENV=/srv/rag/venv"
          Environment="PYTHONPATH=/srv/rag/src"
          WorkingDirectory=/srv/rag/chatbot
          EnvironmentFile=/srv/rag/.env
          ExecStart=/srv/rag/venv/bin/chainlit run app.py --host 0.0.0.0 --port 80
          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/polylex-chatbot.service
      notify:
        - systemd reload
        - Polylex Chatbot restart

    - name: Polylex Chatbot service
      systemd_service:
        name: polylex-chatbot.service
        state: started
        enabled: true
